language: node_js
node_js:
- 4.6.0
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g grunt-cli
notifications:
  slack:
    secure: HAEmhg7D0RgQ4Y+ziGYSxv+uae6/JC9jKPAPneUr1LgKbCqugaGnur5Y16fjv4niOiDTuyBMraA+4Sob/KTYMUny5S2UQZAmSEqV61+Ap22HnFFLy59h63UupdzojJxI2f1P0fvvixrTkpQ08N18rTxfes+krk/sDWk4dzLDZMk6m5Aymob6MRSkUwcYUh4gUwj0KtR07Apl+5Hk7h4DJZUPkJ2G1wYuUDHABZG8ueGy7UvHK0nbouFORK/6NIZf9mdCBs756NK7JUgf5Mj0AAmIvU0V+xFYQIdvArAABE8s7c82KOzMbb+uHRKrdqJQjN2+dUb1w2rbVamMpnr6vCc3hBJN+Msuy8Fl2VRm9xg/g4eupGkRN1REBC5H26uHPFiEiHdFrO2wxn15rqu6yKJD6BeV9Cve5fPkXACgs5IKfXRKdRO/L/AwWcb4LIRe65WmCV/GuxJwamWWpj/lAzeqW7c3n/Pd6/aSRCJpwDYqgEZVJbCRk+wi2TGplzC9DND0WBPFp2O5Oec3W29x4gEfBHKzUmbf0ALyB/FZ03SYGKZIoMer6V1tQIBXBRsiqj+Uun5uPb+UjU0nhe41FYRT5JfNC3ZCn1vGesloAWkjLiT5zmDpdge8HE/ShyAoN3DxHbt3lpCyHWBzoNKWdee2MHmANPuLwqIv01xdOMQ=
